# Generated by Django 4.2.11 on 2025-06-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_usuario_contrasena_usuario_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('docente', 'Docente'), ('alumno', 'Alumno')], default='alumno', max_length=20),
        ),
    ]
